### ISSUE TITLE
D-Rats lzhuf does not work on big-endian systems

### ISSUE THREAD

**Issue by wb8tyw** [ham-radio-software/D-Rats#153]
The lzhuf on D-Rats is not the most current source for the program.

A more current source has been found in the
[G8BPQ/LinBPQ project](https://github.com/g8bpq/LinBPQ/blob/master/lzhuf32.c) .

The version in D-rats assumes that the system is Little-Endian which means that when the program is built on Big-Endian machines, it can not interchange data with actual winlink systems.

**Comment by yo2loj** [comment]
The lzhuf is based on the original implementation to get it working on current windows systems, so no effort was done to migrate it to big endian systems. IMHO it should be endianess-agnostic and produce identical outputs on any system.

Marius, YO2LOJ

August 27, 2022 10:01 PM, "John E. Malmberg" ***@***.*** ***@***.******@***.***>)> wrote:
	The lzhuf on D-Rats is not the most current source for the program. 

	A more current source has been found in the
G8BPQ/LinBPQ project (https://github.com/g8bpq/LinBPQ/blob/master/lzhuf32.c) . 

	The version in D-rats assumes that the system is Little-Endian which means that when the program is built on Big-Endian machines, it can not interchange data with actual winlink systems.
