### ISSUE TITLE
import code 0.3.3 for documentation purposes

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#157]
would be useful to import the latest d-rats code from Dan (0.3.3 or later) and keep it here around for reference purposes?

**Comment by wb8tyw** [comment]
Presumably that code should already be in the repository, we just need to find the commit for it and tag it as a release with out actually creating a release similar to what I did with the compliance commit for the 0.3 branch.

If that is too much work, we can create a repository for it.  I think we can mark it archived which means there will be no more changes made for it.
