### ISSUE TITLE
PKG-INFO

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#180]
@wb8tyw do we still need this file? which tool should use it? 
if to keep it's content should be updated as it refers to d-rats 0.3.x

**Comment by wb8tyw** [comment]
PKG-INFO is being put in the pip installable tarball by the py, and I have not found out what is putting it there from looking at the configuration files.

As near as I can tell, pip does not install that file, use it.

I am not sure that PKG-INFO does for us, and will test the net python -m build with out it being present.  If we do need it, it probably needs to be built with the python_prebuild.py script to have an actual version, so probably not be in the repository.
