### ISSUE TITLE
File transfer  - Mac - unxpected folder being created

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#257]
tested on Mac, ratflector only . it could happen on other systems as well

In files tab, as soon as I connect to a remote  machine an unexpected folder is being created in the directory which hosts the source files. If this has to be it should happen into the configured folder , e.g. somewhere under /Users/maurizio/.d-rats-ev/

See here the folder created as soon as i connected to KG5CE...:
<img width="431" alt="image" src="https://github.com/ham-radio-software/D-Rats/assets/7696314/ed4cc020-925b-484f-a531-37d0d508b9f3">

**Comment by wb8tyw** [comment]
Definitely something that needs to be looked into.
The D-Rats runtime should not be updating any files in the source tree.

**Comment by wb8tyw** [comment]
Only got as far as finding where it is creating the folder.   Not sure why it is creating the folder as it does not seem to use it for anything.
