### ISSUE TITLE
Info popup error on Windows MobaXTerm

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#278]
On D-Rats under mobaxterm , opening the info I get error of missing image of the d.-rats logo:

```
Traceback (most recent call last):

  File "/drives/c/Users/mauri/AppData/Roaming/MobaXterm/home/d-rats-git/d_rats/mainwindow.py", line 258, in _activate_about
    logo = GdkPixbuf.Pixbuf.new_from_file_at_size("images/d-rats2.png", 64, 64)

gi.repository.GLib.GError: g-file-error-quark: Failed to open file 'images/d-rats2.png': No such file or directory (4)
```

**Comment by wb8tyw** [comment]
Not specifically a MobaXterm issue.  The about dialog is using a relative path to the current working directory.

It shows up on MobaXterm because the current working directory is not the d-rats checkout, which is similar to the issue that on MobaXterm the git version detection is also failing.
