### ISSUE TITLE
MobaXterm install script needs to run build_pot.sh script

### ISSUE THREAD

**Issue by wb8tyw** [ham-radio-software/D-Rats#282]
Since the MobaXterm install script uses a git checkout, it needs to run the build_pot.sh script as part of the install, and the install script must make sure any packages needed are installed.

**Comment by maurizioandreotti** [comment]
trying to execute the buildpot I get this error

```
 ./build_pot.sh
+ xgettext -d D-RATS -o locale/base.pot -D . ./d-rats.py ./d-rats_repeater.py ./internationalization_test.py ./plugin_test.py ./python_prebuild.py ./setup.py
./build_pot.sh: line 6: xgettext: command not found

```
