### ISSUE TITLE
Think 010.020 Installation of D‐Rats on Microsoft Windows with MobaXterm should include...

### ISSUE THREAD

**Issue by KP4AJ** [ham-radio-software/D-Rats#284]
Hi Maurizio:
I think the wiki is missing the command to actually execute the installation script. I mean:

**_bash d-rats_in_mobaxterm_install.sh_**

should go after Past chmod 0755 d-rats_in_mobaxterm_install.sh and key in Enter. (which I would label something as 'type chmod 0755 d-rats_in_mobaxtermn.sh and hit Enter').

Assumption here is Windows users with very little knowledge of Linux. 

73'

Edfel
KP4AJ

p.d.
Installed latest version here and seems to work.

**Comment by wb8tyw** [comment]
Somehow the line got dropped in one of the edits.  Fixed now thanks.
