### ISSUE TITLE
Mapwindow - wrong vertical placement on markers for zoom 2-4

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#29]
at zoom 2-4 gpsmarkers are still shown with wrong heighs 

fudge function for zoom 2-4 should now be fine, 

it could be something related to the window size which at that zoom level can now be larger than the map contained producing a wrong offset as reference for the fudge function.

**Comment by wb8tyw** [comment]
D-Rats is no longer using fudge factors and should show now work at any of the supported resolutions.
