### ISSUE TITLE
saving the config - unknow ports messages

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#45]
saving the config one time after making no changes, the display of the program hung and in the terminal, I saw:
--

Msgrouting: Running routing loop
Mainapp   : Station KD2RCQ has unknown port k3pdr rat
Mainapp   : Station NS3K has unknown port k3pdr rat
Mainapp   : Station N2KTO-R has unknown port k3pdr rat
Mainapp   : Station KG5CEN-1 has unknown port k3pdr rat
Mainapp   : Station K3PDR-1 has unknown port k3pdr rat
Mainapp   : Station EA1VIL-1 has unknown port k3pdr rat
Mainapp   : Station N3KDA has unknown port k3pdr rat
Mainapp   : Station KB5HPT has unknown port k3pdr rat
Mainapp   : Station KI6ZHD has unknown port agwpe packet
--

**Comment by wb8tyw** [comment]
I am pretty sure that this got fixed in the python3 port.
